image: 'node:15.4'

stages:
  - deploy

#   # Build and publish to s3 bucket; feature or bugfix branch
publish bug or feature to s3:
  stage: deploy
  environment:
    name: feature
    url: https://s3.console.aws.amazon.com/s3/buckets/platypus-cl-student-templates
  image: sleavely/node-awscli:14.x 
  script:
    - 'echo ${CI_SERVER_HOST}, ${CI_SERVER_URL}, ${CI_PROJECT_ROOT_NAMESPACE}'
    - npm config set -- '//gitlab.tvo.org/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - "yarn"
    - "cd amp-template-generator"
    - "npm install"
    - "cd .."
    - "npm run test-templates"
    - "cd amp-template-generator"
    - "npm run build"
    - cd build
    - aws s3 sync . s3://platypus-cl-student-templates/$CI_COMMIT_BRANCH --exclude "node_modules" --include "*"
    
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
  when: manual

