version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci 
      - echo Running tests
      - npm run test

  build:
    commands:
      - echo Building project...
      - echo Build started on `date`
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: "dist"

cache:
  paths:
    - "/node_modules/"

